### ISSUE TITLE
Python3 Compatibility and Launch error

### ISSUE THREAD

**Issue by abbasvalliani** [nigelb/Static-UPnP#1] opened 2016-12-10 22:42 UTC
After fixing some compile issues with python3, I am receiving the following error:

Traceback (most recent call last):
  File "/usr/local/bin/static_upnp", line 9, in <module>
    load_entry_point('static-upnp==0.0.1', 'console_scripts', 'static_upnp')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.5/dist-packages/static_upnp-0.0.1-py3.5.egg/static_upnp/static.py", line 24, in <module>
    from static_upnp.upnp_reciever import UPnPServiceResponder
  File "/usr/local/lib/python3.5/dist-packages/static_upnp-0.0.1-py3.5.egg/static_upnp/upnp_reciever.py", line 26, in <module>
    import ip, udp
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 896, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1139, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1115, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1096, in _legacy_get_spec
  File "<frozen importlib._bootstrap>", line 444, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 533, in spec_from_file_location
  File "/usr/local/lib/python3.5/dist-packages/pyip-0.7-py3.5.egg/ip.py", line 173
    raise ValueError, "invalid source address"
                    ^
SyntaxError: invalid syntax

**Comment by nigelb** [comment] 2016-12-11 01:36
The problem is that pyip does not support python3. Fortunately I was only using it to experiment with spoofing addresses, which turned out to be unnecessary. Have a look at the python3 branch it seems to work for me, though there is something hinky with the shutdown in python3.

**Comment by nigelb** [comment] 2017-01-06 12:42
Merged python3 branch.

**Closed as completed** 2017-01-06 12:42 UTC
